<a href="https://colab.research.google.com/github/sehrish30/numpy-Practice/blob/main/7_Python_101_Python_Libraries_for_Data_Analysis_Numpy_Skeleton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NUMPY BASICS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np

# Let's define a one-dimensional array 
my_list = [10, 20, 50, 60, 70]
my_list

[10, 20, 50, 60, 70]

In [3]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [4]:
type(x)

numpy.ndarray

# Multi-dimensional (Matrix definition) 
matrix = np.array([[5, 8], [9, 13]])
matrix

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [13]:
x = np.array([[4, 6, 8, 7], [20, 5, 6, 9]])
print(x)

[[ 4  6  8  7]
 [20  5  6  9]]


# 2. BUILT-IN METHODS AND FUNCTIONS 

In [14]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(15)
x

array([0.94963232, 0.58724727, 0.79221599, 0.99603697, 0.07651114,
       0.02984163, 0.06944947, 0.64131252, 0.58919958, 0.76037026,
       0.7394587 , 0.93930968, 0.85902343, 0.99661037, 0.32576964])

In [16]:
# you can create a matrix of random number as well
x = np.random.rand(5, 5)
x

array([[1.20428471e-01, 3.63767247e-01, 1.18964083e-01, 3.63836812e-02,
        3.89204812e-02],
       [4.82622148e-02, 7.19136767e-02, 3.11276730e-01, 7.51261863e-01,
        2.51516458e-01],
       [9.14961308e-01, 4.65230796e-01, 1.07633973e-01, 7.89549832e-01,
        8.44930843e-04],
       [6.00898306e-01, 3.30123366e-01, 8.68017953e-01, 1.13469056e-01,
        9.61913889e-01],
       [5.29381318e-01, 8.37618821e-01, 5.55673839e-01, 4.49666951e-01,
        3.35408246e-02]])

In [17]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x

array([-0.46221399, -0.17551525, -0.64196301, -0.5780721 , -0.57317859,
       -1.46336556,  0.92206894, -2.0134433 , -0.06468905,  1.03926172])

In [18]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1 , 10)
x

3

In [19]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([53,  2, 63, 87, 72, 16, 87, 75, 18, 42, 61, 58, 73, 91, 56])

In [21]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
# Create an evenly spaced values with a step of 5
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [25]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(10)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
# Array of ones
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
# Matrices of ones
x = np.ones((10, 10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
# Array of zeros
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [33]:
x = int(input('Please enter a positive integer value'))
x = np.random.randint(1, x, 20)
x

Please enter a positive integer value10


array([2, 1, 1, 1, 6, 1, 6, 8, 6, 4, 2, 1, 1, 3, 4, 4, 4, 6, 7, 8])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [ ]:
# Let's define a one-dimensional array 


In [ ]:
# Get Length of a numpy array


In [ ]:
# Get shape


In [ ]:
# Obtain the datatype


In [ ]:
# Reshape 1D array into a matrix


In [ ]:
# Obtain the maximum element (value)


In [ ]:
# Obtain the minimum element (value)


In [ ]:
# Obtain the location of the max element


In [ ]:
# Obtain the location of the min element


**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

# 4. MATHEMATICAL OPERATIONS

In [ ]:
# np.arange() returns an evenly spaced values within a given interval


In [ ]:
# Add 2 numpy arrays together


**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

# 5. SLICING AND INDEXING 

In [ ]:
# Access specific index from the numpy array


In [ ]:
# Starting from the first index 0 up until and NOT inlcluding the last element


In [ ]:
# Broadcasting, altering several values in a numpy array at once


In [ ]:
# Let's define a two dimensional numpy array


In [ ]:
# Get a row from a mtrix


In [ ]:
# Get one element


**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X